### ISSUE TITLE
Switch image creation from jib to Spring Boot maven plugin

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#235]
Currently generated apps use jib to build their container images. We want to replace usage of jib with Spring Boot Maven plugin (or possibly raw Paketo).

We are using SBMP in SCDF samples and it works well. In [SCDF raw Paketo](https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/.github/actions/build-images/action.yml#L27) is used as it has much flexibility (base images, tags, etc..). 

### TODO
- [x] Tradeoff analysis between Packeto and SBMP
- [x] Decide on P or SBMP
- [ ] Make changes to generator and update builds accordingly

**Comment by sobychacko** [comment]
@jvalkeal @markpollack @onobc Let us discuss the pros/cons of this approach and decide how to proceed here.
cc @dturanski @artembilan

**Comment by sobychacko** [comment]
We use the baseimage from this repository. See the usage of this script: https://github.com/spring-cloud/baseimage/blob/main/wait-for-it.sh

**Comment by onobc** [comment]
This is now in latest CI (2021.1.x and main)
