### ISSUE TITLE
Convert Apps to Functions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/stream-applications#56]
Following artifacts/apps need to be released as part of the Fahrenheit GA release train. 

List sorted by maven-central's download frequency aka a rough take on priority:

- [x] http-source  - @artembilan @sobychacko
- [x] rabbit-source  - 
- [x] rabbit-sink  - @sobychacko 
- [x] gemfire-source  - 
- [x] gemfire-sink  - **ready** @tzolov 
- [x] gemfire-cq-source - 
- [x] log-sink - @sobychacko
- [x] jdbc-source  - @sobychacko
- [x] jdbc-sink  - @sobychacko 
- [x] ftp-source -  @sobychacko 
- [x] ftp-sink - 
- [x] mongodb-source - @dturanski @sobychacko Fahrenheit-M2
- [x] mongodb-sink - @dturanski @sobychacko Fahrenheit-M2
- [x] sftp-source -  @dturanski _(in-progress)_ 
- [x] sftp-sink -   
- [x] router-sink - (app only)
- [x] counter-sink - @tzolov Fahrenheit-M2
- [x] splitter-processor - @artembilan @sobychacko
- [x] time-source - @sobychacko 
- [x] httprequest-processor - @dturanski 
- [x] filter-processor 
- [x] transform-processor  
- [x] bridge-processor - (app only)
- [x] jms-source  - @sobychacko 
- [x] tcp-source 
- [x] tcp-sink 
- ~~[ ] tcp-client-source    - (app only)~~
- ~~[ ] tcp-client-processor    - (app only)~~
- [x] groovy-processor - (app only) 
- [x] header-enricher-processor
- [x] s3-source  
- [x] s3-sink  
- [x] file-source  - @artembilan 
- [x] file-sink  - @artembilan 
- [x] mqtt-source
- [x] mqtt-sink
- [x] aggregator-processor - @artembilan 
- [x] cassandra-sink - @artembilan @sobychacko 
- [x] load-generator-source - (app only)
~- [ ] loggregator-source - (app only)~
- [x] mail-source -  @artembilan @sobychacko
- [x] pgcopy-sink  - @sobychacko
- [x] redis-pubsub-sink - function ready
- [x] script-processor - (app only)
- [x] syslog-source   - @sobychacko
- [x] throughput-sink - (app only)
~- [ ] trigger-source   - (app only)~
- [x] twitterstream-source  - check with Christian.
- [x] image-recognition-processor - check with Christian.
- [x] pose-estimation-processor - check with Christian.
- [x] tasklaunchrequest-transform-processor (function only) - Dave
- [x] tasklauncher-dataflow -> tasklauncher - @dturanski _(in pr)_ Dave
- [x] tensorflow-processor - check with Christian.
- [x] twitter-sentiment-processor - check with Christian.
- [x] object-detection-processor - check with Christian.
- [x] websocket-source
- [x] websocket-sink
